#!/bin/python
import subprocess
import sys

def minShell():
    for cmd in sys.stdin:
        if(cmd=="logout\n"):
            return
        subprocess.run(cmd, shell=True)

def main():
    minShell()
    print("Terminated")

if __name__ == "__main__":
    main()
