#!/bin/python3
import subprocess
import binascii
import sys
import os

ELF_MAGIC="7f454c46020101000000000000000000"

def isElf(file):
    magic=getMagic(file)
    if magic == ELF_MAGIC:
        return True
    return False

def getMagic(file):
    tmp=""
    with open(file, "rb") as myBin:
        header=myBin.read(24)
        tmp=str(binascii.hexlify(header))[2:34]
    return tmp

def main(directory):
    for ent in os.listdir(directory):
        filePath=os.path.join(directory, ent)
        if os.path.isdir(filePath):
            continue
        if isElf(filePath):
            continue
        if ent=="execNoElf":
            continue
        try:
            subprocess.call(filePath)
        except:
            continue

if __name__ == "__main__":
    if len(sys.argv) < 2:
        main(os.getcwd())
    else:
        main(sys.argv[1])
